---
title: "Comparison of Sampling Methods"
author: "Jingze Dai"
---
In this notebook, we will conduct a simplified analysis to compare the different sampling methods in the dataset.

```{r}
# importing libraries
library(tidyverse)
library(here)
library(dplyr)
library(tidyr)
library(lubridate)
library(sf)
library(leaflet)
library(mapview)
library(RColorBrewer)
here()
```


```{r}
# importing dataset
microplastics <- read.csv(here("Data/Raw/Marine_microplastics.csv"))
```


```{r}
microplastics$Sampling.Method <- as.factor(microplastics$Sampling.Method)
summary(microplastics$Sampling.Method)
```


```{r}
microplastics_selected <- microplastics %>% 
  filter(Sampling.Method == c("Hand picking", "Neuston net", "Manta net", "Grab sample", "PVC cylinder"))
```



```{r}
microplastics$Unit <- as.factor(microplastics$Unit)
summary(microplastics$Unit)
```


```{r}
pieces_per_kg_dw <- microplastics %>% 
  filter(Unit == "pieces kg-1 d.w.") %>% 
  group_by(Sampling.Method)

pieces_per_10mins <- microplastics %>% 
  filter(Unit == "pieces/10 mins") %>% 
  group_by(Sampling.Method)

pieces_per_m_cube <- microplastics %>% 
  filter(Unit == "pieces/m3") %>% 
  group_by(Sampling.Method)
```


```{r}
summary(pieces_per_kg_dw$Sampling.Method)
```


```{r}
summary(pieces_per_10mins$Sampling.Method)
```


```{r}
summary(pieces_per_m_cube$Sampling.Method)
```

```{r}
neuston_net <- pieces_per_m_cube %>% 
  filter(Sampling.Method == "Neuston net")

sea_pump <- pieces_per_m_cube %>% 
  filter(Sampling.Method == "Intake seawater pump")

manta_net <- pieces_per_m_cube %>% 
  filter(Sampling.Method == "Manta net")

van_dorn <- pieces_per_m_cube %>% 
  filter(Sampling.Method == "Van Dorn sampler")

pvc_cylinder <- pieces_per_m_cube %>% 
  filter(Sampling.Method == "PVC cylinder")

grab_sample <- pieces_per_m_cube %>% 
  filter(Sampling.Method == "Grab sample")

selected_sampling <- rbind(neuston_net, manta_net,grab_sample)

```



```{r}
boxplot_sampling <- ggplot(selected_sampling,
                  aes(x = Sampling.Method, y = Measurement)) +
  geom_boxplot() +
  labs(title = "Sampling method", y = "Measurement (pieces/m^3)")

boxplot_sampling
```

